# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
