# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 22:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hubdata', '0002_delivery_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.IntegerField()),
                ('price', models.FloatField(default=0.0)),
                ('lat', models.FloatField(default=0)),
                ('long', models.FloatField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('email', models.EmailField(default='', max_length=254)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubdata.Hub')),
            ],
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='customer',
        ),
        migrations.DeleteModel(
            name='delivery',
        ),
    ]
