# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubdata', '0003_auto_20170804_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='dstatus',
            field=models.BooleanField(default=False),
        ),
    ]
